"""add fks and constraints

Revision ID: 326478402721
Revises: 
Create Date: 2025-09-07 11:12:48.061266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326478402721'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use batch operations for SQLite constraints
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_daily_stats_user_date', ['user_id', 'date'])
        batch_op.create_foreign_key('fk_daily_stats_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_usage_events_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.add_column('users', sa.Column('focus_sensitivity', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('show_overlays', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('monitored_websites', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usage_events_user', type_='foreignkey')

    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_constraint('fk_daily_stats_user', type_='foreignkey')
        batch_op.drop_constraint('uq_daily_stats_user_date', type_='unique')

    op.drop_column('users', 'monitored_websites')
    op.drop_column('users', 'enabled')
    op.drop_column('users', 'show_overlays')
    op.drop_column('users', 'focus_sensitivity')
    # ### end Alembic commands ###
